LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/HouseholdMembersData.csv'
INTO TABLE householdmember
CHARACTER SET utf8
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS;